#!/usr/bin/env python3
"""
Cycle through N randomly-generated joint configurations via dynamic reconfigure.

Every `interval_s` seconds the next configuration is pushed to
/girona_controller as nominal_config_1..6 (converted from degrees to radians).

Configurations are generated by generate_configurations() from
generate_20_configurations.py using the same seed so results are reproducible.

Usage:
    rosrun sensorless_force_control cycle_nominal_configurations.py
"""

import math
import rospy
from dynamic_reconfigure.client import Client as DynClient
from generate_20_configurations import generate_configurations


def deg2rad(deg: float) -> float:
    return deg * math.pi / 180.0


def run():
    rospy.init_node("cycle_nominal_configurations", anonymous=False)

    n_configs   = rospy.get_param("~n_configs",   50)
    interval_s  = rospy.get_param("~interval_s",  3.0)
    seed        = rospy.get_param("~seed",         10)
    controller  = rospy.get_param("~controller",  "/girona_controller")

    rospy.loginfo(f"[cycle_nominal] generating {n_configs} configs (seed={seed})")
    configs_deg = generate_configurations(n_configs, seed=seed)

    dyn = DynClient(controller, timeout=10.0)
    rospy.loginfo(f"[cycle_nominal] connected to {controller}")

    rate = rospy.Rate(1.0 / interval_s)

    for idx, q_deg in enumerate(configs_deg):
        if rospy.is_shutdown():
            break

        q_rad = [deg2rad(v) for v in q_deg]

        cfg = {
            "nominal_config_1": q_rad[0],
            "nominal_config_2": q_rad[1],
            "nominal_config_3": q_rad[2],
            "nominal_config_4": q_rad[3],
            "nominal_config_5": q_rad[4],
            "nominal_config_6": q_rad[5],
        }
        dyn.update_configuration(cfg)

        rospy.loginfo(
            f"[cycle_nominal] [{idx+1}/{n_configs}]  "
            f"q=[{', '.join(f'{v:.1f}' for v in q_deg)}] deg  "
            f"(next update in {interval_s:.0f} s)"
        )

        rate.sleep()

    rospy.loginfo("[cycle_nominal] all configurations sent.")


if __name__ == "__main__":
    try:
        run()
    except rospy.ROSInterruptException:
        pass